# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target '2019-11-03-About-GCD-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2019-11-03-About-GCD-Example
  pod 'TinyConstraints'

end
