# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'usingFirebaseGoogleLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'  
  pod 'FirebaseUI'  
  
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods  

  # Pods for usingFirebaseGoogleLogin

end
