# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target '2019-10-25-UIImagePickerExample-rebeloper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2019-10-25-UIImagePickerExample-rebeloper
pod 'TinyConstraints'

end
